# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

# title = "Hugo FixIt Blog"
# baseURL = "https://hugo-fixit.github.io/hugo-fixit-starter/"
# # theme = "FixIt"
# defaultContentLanguage = "en"
# languageCode = "en"
# hasCJKLanguage = true
# enableRobotsTXT = true
# enableEmoji = true
# enableGitInfo = true
# relativeURLs = false
# buildDrafts = false
# summaryLength = 150
# # ignore some build errors
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

title: Hugo FixIt Blog
baseURL: 127.0.0.1:1313
# 默认语言设置 en/zh-cn
defaultContentLanguage: zh-cn
languageCode: en
hasCJKLanguage: true
enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true
relativeURLs: false
buildDrafts: false
summaryLength: 150
ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken
