# -------------------------------------------------------------------------------------
# Modules Configure
# See: https://gohugo.io/hugo-modules/configuration/#module-config-imports
# -------------------------------------------------------------------------------------

imports:
  - path: "github.com/hugo-fixit/FixIt"
    version: main
  - path: github.com/Lruihao/hugo-shortcode-mmt-netease
    version: main
  - path: github.com/hugo-fixit/cmpt-translate
    version: main
  - path: github.com/Artexxx/cmpt-post-preview
    version: main
hugoVersion:
  extended: true
  #min: 0.112.0


# [[imports]]
#   path = "github.com/hugo-fixit/FixIt"

# [hugoVersion]
#   extended = true
#   min = "0.112.0"
