# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

posts: "posts/:slugorfilename"

# posts = ":year/:month/:filename"
# posts = "posts/:slugorfilename"
