# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

# 网站标题
title: "毕少侠"
baseURL: "https://geekswg.js.cool/blog-fixit-go/"
